apiVersion: v1
kind: LimitRange
metadata:
  name: cont-limit-range
  namespace: dia04i
spec:
  limits:
  - type: Container
    default:
      memory: 256Mi
      cpu: 0.3
    defaultRequest:
      memory: 128Mi
      cpu: 0.1
    max:
      memory: 260Mi
      cpu: 0.5
    min:
      memory: 128Mi
      cpu: 0.1