apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: segunda-quota
  namespace: dia04i
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.cpu: "1"
    requests.memory: 1Gi
status: {}
