apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-com-recreate
  name: deploy-com-recreate
  namespace: dia01i
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-com-recreate
  strategy: 
      type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-com-recreate
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
        resources: {}
status: {}
