apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-desafio02
  name: pod-desafio02
  namespace: dia01i
spec:
  containers:
  - image: nginx
    name: pod-desafio02
    env:
    - name: chave2
      valueFrom:
        configMapKeyRef:
          name: configmap-desafio02
          key: chave2
    - name: chave3
      valueFrom:
        configMapKeyRef:
          name: configmap-desafio02
          key: chave3
    - name: chave4
      valueFrom:
        configMapKeyRef:
          name: configmap-desafio02
          key: chave4
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
