apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-com-cmvolume
  name: pod-com-cmvolume
  namespace: dia01i
spec:
  containers:
  - image: nginx
    name: pod-com-cmvolume
    volumeMounts:
    - name: configmap-volume
      mountPath: /etc/config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: configmap-volume
    configMap:
      name: configmap-volume
status: {}
