apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-com-configmap-unico
  name: pod-com-configmap-unico
  namespace: dia01i
spec:
  containers:
  - image: nginx
    name: pod-com-configmap-unico
    env:
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: configmap-primeiro
          key: DATABASE_URL
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
