apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/exports/volumenfs
    server: 172.16.1.103
  storageClassName: sc-nfs
  persistentVolumeReclaimPolicy: Retain