apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-longhorn
  namespace: dia01a  
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi