apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: desafio15-apache-vm
  name: desafio15-apache-vm
  namespace: dia03i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio15-apache-vm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: desafio15-apache-vm
        desafio: '15'
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - vm
status: {}
