apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: desafio15-backend
  name: desafio15-backend
  namespace: dia03i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio15-backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: desafio15-backend
        desafio: '15'        
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - desafio15-frontend
              topologyKey: "kubernetes.io/hostname"   
status: {}
