apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: intranet-production
  name: intranet-production
  namespace: desafio22
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intranet-production
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: intranet-production
    spec:
      containers:
      - image: apache
        name: apache
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.5
            memory: 386Mi
          requests:
            cpu: 0.2
            memory: 300Mi
      priorityClassName: production
status: {}
