apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: production
value: 1000000
globalDefault: false
description: "Esta PriorityClass deve ser utilizada para os Pods do ambiente de production."

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: stage
value: 500000
globalDefault: false
description: "Esta PriorityClass deve ser utilizada para os Pods do ambiente de stage."

---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: development
value: 100000
globalDefault: false
description: "Esta PriorityClass deve ser utilizada para os Pods do ambiente de development."