apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: desafio16-nodeport
  name: desafio16-nodeport
  namespace: dia03i
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio16-nodeport
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: desafio16-nodeport
        desafio: '16'
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
