apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-scale
  name: nginx-scale
  namespace: hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-scale
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-scale
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 25Mi
            cpu: 1m
          limits:
            memory: 300Mi
            cpu: 2m
status: {}
