apiVersion: v1
kind: LimitRange
metadata:
  name: cont-limit-range
  namespace: dia03i
spec:
  limits:
  - type: Container
    default:
      memory: 256Mi
      cpu: 0.3
    defaultRequest:
      memory: 12Mi
      cpu: 0.1