apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: desafio14
  name: desafio14
  namespace: dia03i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio14
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: desafio14
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: OS
                operator: In
                values:
                - XPTO
status: {}
