apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: primeiro-service
  name: primeiro-service
  namespace: dia03i
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: primeiro-service
status:
  loadBalancer: {}
