apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-nodeport
  name: service-nodeport
  namespace: dia03i
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: service-nodeport
  type: NodePort
status:
  loadBalancer: {}
