apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trabalho-com-affinity
  name: trabalho-com-affinity
  namespace: dia03i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trabalho-com-affinity
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trabalho-com-affinity
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: OS
                operator: In
                values:
                - XPTO
status: {}
