apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: conexao-registry
  name: conexao-registry
  namespace: dia02i
spec:
  containers:
  - image: danielynx/helloworld-dotnet:latest
    name: conexao-registry
    resources: {}
  imagePullSecrets:
  - name: docker-hub-file
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
