apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-todas-probes
  name: deploy-todas-probes
  namespace: dia02i
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-todas-probes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-todas-probes
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5     
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /k8s
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3                    
status: {}
