apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-readiness
  name: deploy-readiness
  namespace: dia02i
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-readiness
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-readiness
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 3
status: {}
