apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deploy-liveness
  name: deploy-liveness
  namespace: dia02i
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-liveness
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-liveness
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        livenessProbe:
          httpGet:
            path: /almt
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
status: {}
