apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-secret-env
  name: pod-secret-env
  namespace: dia02i
spec:
  containers:
  - image: nginx
    name: pod-secret-env
    envFrom:
    - secretRef:
        name: environment-production
    - secretRef:
        name: environment-development   
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
