apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-com-duas-secrets
  name: pod-com-duas-secrets   
  namespace: dia02i
spec:
  containers:
  - image: nginx
    name: pod-com-duas-secrets
    volumeMounts:
    - name: secrets
      mountPath: "/etc/secrets"
    resources: {}
  volumes:
  - name: secrets
    projected:
      sources:
      - secret:
          name: primeiro-secret
      - secret:
          name: primeiro-secret-env 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
