apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-com-secret-env
  name: pod-com-secret-env
  namespace: dia02i
spec:
  containers:
  - image: nginx
    name: pod-com-secret-env
    volumeMounts:
    - name: primeiro-secret-env
      mountPath: "/etc/secrets"    
    resources: {}
  volumes:
  - name: primeiro-secret-env
    secret:
      secretName: primeiro-secret-env    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
