apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-com-secret
  name: pod-com-secret
  namespace: dia02i
spec:
  containers:
  - image: nginx
    name: pod-com-secret
    volumeMounts:
    - name: primeiro-secret
      mountPath: "/etc/secrets"
    resources: {}
  volumes:
  - name: primeiro-secret
    secret:
      secretName: primeiro-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
