apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: desafio18-green
  name: desafio18-green
  namespace: dia03i
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio18-green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: desafio18-green
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
        resources: {}
status: {}
