apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: desafio18
  name: desafio18
  namespace: dia03i
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: desafio18-blue
  type: LoadBalancer
status:
  loadBalancer: {}
