apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: desafio18-blue
  name: desafio18-blue
  namespace: dia03i
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desafio18-blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: desafio18-blue
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
