apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: curso.almt.io
spec:
  group: almt.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nomeAluno:
                  type: string
                curso:
                  type: string
                nota:
                  type: integer
  scope: Namespaced
  names:
    plural: curso
    singular: curso
    kind: Curso
    shortNames:
    - cur