apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storage.almt.io
spec:
  group: almt.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                size:
                  type: integer
                filesystem:
                  type: string
  scope: Namespaced
  names:
    plural: storage
    singular: storages
    kind: Storage
    shortNames:
    - st